version: "3.3"
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src/
    environment:
      MONGODB_URI: mongodb://mongodb:27017/nds
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
  mongodb-gui:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/nds
    depends_on:
      - mongodb
volumes:
  mongo-data:
